GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQ3MTE2ODk4LCJleHAiOjE2NDcxMTY5MTN9.GRRN-ojMMn3ZPW6OMmzNcoSzhFsJrTX7DhyQMc5J8M0

###

DELETE http://localhost:4000/logout 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQ3MTE2NzYzfQ.zd4Ogzvv8_lokfIharmGd3YRXppoSPdxCBXI0luRRmg"
}

###

POST http://localhost:4000/token 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQ3MTE2NzYzfQ.zd4Ogzvv8_lokfIharmGd3YRXppoSPdxCBXI0luRRmg"
}

###

POST http://localhost:4000/login 
Content-Type: application/json

{
"username": "Jim"
}